Linear interpolation is a method used to estimate an unknown value that falls between two known values. This method assumes that the unknown value falls on a straight line or linear function between the two known values.
Linear interpolation can be visually represented as:
Figure 5.1: An unknown point P between two known points A and B.
Essentially, linear interpolation works by drawing a straight line between the two points and then finding the value of the function at a point along that line.
Mathematically, for two known points (x0, y0) and (x1​, y1​), the linear interpolation formula to estimate the value y at a point x is:
y=y0+(x−x0)(y1−y0x1−x0)y = y_{0} + \left( x - x_{0} \right)\left( \frac{y_{1} - \ y_{0}}{x_{1} - x_{0}} \right)
Interpolation is used heavily in mechanical engineering for subjects such as thermodynamics and fluid dynamics but is also used in computer graphics, finance, geosciences, economics and statistics, manufacturing, and navigation.
To demonstrate calculating linear interpolation in DAX, paste the following into a Blank query in Power Query Editor using the Advanced Editor to completely replace the contents of the query. Call the query TempPressure.
let  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("NZLLjUMxDAN7eefAMPW1agm2/zb2RaJPQSa0PaLy/T57bTyf38feAeTz9/k+fslJiSbYRBA5Q24IuScjNyOqNeRmlBfrjZgYyY14yByym0k9PuRmymuIMwNRAkbgOTJxE8UjwYT4tgbJhELmOwN65obD3y0NAxjwPONeTOTGdFJMHAuwtolgYx4Fi4QpAVtD8VKwI8mtA1iIBpzND7CMMQeHDRwCzpYlBD0Mfrvh9mqAuAuXN8DduDsMqJ0jJm0qS1Hctw7IyplW2lSXWtz9D6hrKm1qK0pmOGlTX85hpUVjGYKPtGguM3asLXqWn5xHtEVrnfDR0BbFO9yZjrVFIes472hRvB6bR1oUsZx/Qm1RnBX00BaVt0LjpfnO9du3yNrxsr9/", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Temp (C)" = _t, #"Pressure (MPa)" = _t]),  #"Changed Type" = Table.TransformColumnTypes(Source,{{"Temp (C)", Int64.Type}, {"Pressure (MPa)", type number}}) in  #"Changed Type"  Alternatively, import the TempPressure sheet from the Excel spreadsheet, Chapter5_Data.xlsx which can be found in the GitHub repository for this book: https://github.com/gdeckler/DAX-For-Humans/tree/main/book.
This table includes temperature and pressure values of water from .01 degree Celsius to 373.95 degrees Celsius. Increments vary but are generally 5 or 10 degrees Celsius. We can construct a second interpolation table for all whole number degree values of Celsius between 1 and 373 degrees by doing the following:
Create a calculated table using this formula:
Interpolation =  SELECTCOLUMNS(  GENERATESERIES( 1, 373, 1 ),  "Temp (C)", [Value]  )  Now create a calculated column in the Interpolation table with this formula:
Pressure (MPa) =  VAR __Temp = [Temp (C)]  VAR __Pressure = MAXX( FILTER( 'TempPressure', [Temp (C)] = __Temp ), [Pressure (MPa)] )  VAR __Result =  IF(  ISBLANK( __Pressure ),  VAR __x0 = MAXX(FILTER('TempPressure',[Temp (C)]  VAR __x1 = MINX(FILTER('TempPressure',[Temp (C)]>__Temp ), [Temp (C)] )  VAR __y0=MAXX(FILTER('TempPressure',[Temp (C)]=__x0),[Pressure (MPa)] )  VAR __y1=MAXX(FILTER('TempPressure',[Temp (C)]=__x1),[Pressure (MPa)] )  VAR __Result = __y0+(__Temp - __x0) * DIVIDE(__y1 - __y0, __x1 - __x0 )  RETURN  __Result,   __Pressure  ) RETURN  __Result  This formula first checks if there is a known value for __Pressure. If there is a known value, then the formula returns that value. Otherwise, the formula “looks up” the values of the closest temperature both greater than and less than the current row’s temperature (__Temp). This is done in the __x0 and __x1 variables.
Once these values are known, the pressures at those temperatures can also be looked up, __y0 and __y1. Finally, the linear interpolation function is used to determine the approximate value of the pressure at the current temperature.
Create a scatter plot using the TempPressure table with the Temp (C) column as the X-axis and the Pressure (MPa) as the Y-Axis. Set both columns to Don’t summarize. Repeat this procedure with the Interpolation table.
Figure 5.2: Non-interpolated (left) versus interpolated (right) data.
As you can see, the original table on the left has gaps between known values. The interpolated data on the right smooths out and fills in these gaps in the data. While the overall shape of the function is quadratic, the small gaps between known data points can be approximated as straight lines (linear).
This completes our exploration of linear interpolation. Let’s next look at another mathematical method known as linear regression.